# First create the react build
FROM node:latest as build-step
WORKDIR /app
COPY package.json yarn.lock ./
COPY . ./
COPY src src
RUN yarn install
RUN yarn vite build

# build nginx
FROM nginx:latest
COPY --from=build-step /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]