name: Testing

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./code/backend
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Pipenv
        run: pip install pipenv
      - name: Test with pytest
        run: |
          pipenv install
          pipenv run pytest
